name: Deploy
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Install Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Install step
              run: deno install

            - name: Build step
              run: deno task build

            - name: Verify build output
              run: |
                  echo "Checking build output..."
                  ls -la out/
                  if [ ! -f "out/main.mjs" ]; then
                      echo "Error: main.mjs not found in out directory!"
                      echo "Contents of out directory:"
                      find out/ -type f
                      exit 1
                  fi
                  echo "Build verification successful - main.mjs found"

            - name: Upload to Deno Deploy
              uses: denoland/deployctl@v1
              with:
                  project: finxol-auth
                  entrypoint: main.mjs
                  root: ./out
                  include: out/*
